version: "3.2"
services:
  nodejs:
    build: 
      context: .
    image: newapp
    networks:
      - frontend
      - backend
    environment:
      - MYSQL_HOST=app-mysql
      - MYSQL_USER=myuser
      - MYSQL_PASS=mypass
      - MYSQL_DB=bank_db
    volumes:
      - ./www/:/var/www/html/
    ports:
      - "8000:8000"
    container_name: newapp
  mysql:
    image: mysql:5.7
    networks:
      - backend
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=myuser
      - MYSQL_PASSWORD=mypass
      - MYSQL_DATABASE=bank_db
    container_name: app-mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    depends_on:
      - mysql
    networks:
      - backend
    ports:
      - "30008:80"
    environment:
      - PMA_HOST=app-mysql
      - PMA_PORT= 3306
    volumes:
      - /sessions
    container_name: app-phpmyadmin
networks:
  frontend:
  backend: